<?php require_once("../constants.php"); ?>
ITCROWD_URL_API = "<?php echo(ITCROWD_URL_API); ?>";
ITCROWD_URL_API_DATA = "<?php echo(ITCROWD_URL_API_DATA); ?>";
ITCROWD_URL_API_TICKET = "<?php echo(ITCROWD_URL_API_TICKET); ?>";
ITCROWD_URL_API_TICKETS = "<?php echo(ITCROWD_URL_API_TICKETS); ?>";
ITCROWD_URL_API_TICKET_EVENTS = "<?php echo(ITCROWD_URL_API_TICKET_EVENTS); ?>";
ITCROWD_URL_API_TICKET_STATE = "<?php echo(ITCROWD_URL_API_TICKET_STATE); ?>";
ITCROWD_URL_API_TICKET_OPERATOR = "<?php echo(ITCROWD_URL_API_TICKET_OPERATOR); ?>";
ITCROWD_URL_API_TICKET_MESSAGE = "<?php echo(ITCROWD_URL_API_TICKET_MESSAGE); ?>";